name: Test and build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  test_and_build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r src/requirements.txt
    
    - name: Test with pytest
      working_directory: src
      run: pytest test.py
